from omegaconf import DictConfig

from cell_graphs.common.utils.config import run
from cell_graphs.configs.cv.cv_config import CVMainConfig


def cv(config: CVMainConfig, zen_cfg: DictConfig) -> None:
    """Run cross-validation with a given config.

    Args:
    ----
        config: Cross-validation config to run.
        zen_cfg: Un-instantiated config generated by hydra-zen used for configuring training.
    """
    config.cv.run(zen_cfg.config.train_config)


if __name__ == "__main__":
    import cell_graphs.configs.stores.cv
    import cell_graphs.configs.stores.shared  # noqa: F401

    run(cv)
